version: "3.9"

services:
  web:
    build: .
    container_name: web
    command: python /data_link_api/data_link/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb


  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"


  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres


  mongodb:
    container_name: mongodb
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"

